### ISSUE TITLE
No need for the react-router package and only install react-router-dom

### ISSUE THREAD

**Issue by leeallen337** [mohandere/cra-boilerplate#1]
I'm pretty certain that as of v4. You don't need to actually install `react-router` itself and should only be installing `react-router-dom` (if you're building for the web). If you look at the `Note` section under the `react-router` Installation section [here](https://github.com/ReactTraining/react-router/tree/master/packages/react-router#installation) you will see that the `react-router` package gets installed as a dependency and you shouldn't be installing it directly 👍

**Comment by mohandere** [comment]
@leeallen337 Thank you. Good catch. I will remove it.
