### ISSUE TITLE
react-redux-toastr

### ISSUE THREAD

**Issue by cbschuld** [mohandere/cra-boilerplate#2]
@mohandere - did you mean to include react-redux-toastr?  I noticed the component under the footer as well.  Just not sure if this was supposed to be in the main app?

BTW, great work on this, I am snagging a copy to bootstrap something; I liked how you organized this - it will save some work!

**Comment by mohandere** [comment]
@cbschuld Thank you so much! I really appreciate your feedback! I kept it intentionally for a demo purpose but yeah we can remove it as its not aligned with project goal.
